// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  category: dynamic(() => import("./Category")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  hero_section: dynamic(() => import("./HeroSection")),
  our_value: dynamic(() => import("./OurValue")),
  packaging: dynamic(() => import("./Packaging")),
  popular_products: dynamic(() => import("./PopularProducts")),
  products: dynamic(() => import("./Products")),
};
